Create table usuario (
	ID INT IDENTITY(1,1) PRIMARY KEY, 
	Nome VARCHAR(255) NOT NULL,
	ValorHora DECIMAL(10,2) NOT NULL DEFAULT 0,
	DataCadastro DATETIME DEFAULT GETDATE(),
	Ativo BIT NOT NULL DEFAULT 1
);